### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by xiaozhu001** [0xSpaceShard/starknet-hardhat-example#127]
Error: Unsupported combination of platform (darwin) and architecture (x64). Consider using a custom compiler (cairo1BinDir in config).

<img width="1081" alt="image" src="https://github.com/0xSpaceShard/starknet-hardhat-example/assets/31197436/f92c4a3e-148c-4dd7-a91d-e924e09c6a1b">

**Comment by FabijanC** [comment]
If you check the [releases](https://github.com/starkware-libs/cairo/releases) page of the cairo compiler repository, you can see that each version has some assets. These are pre-built binaries, but only for some platform-architecture combinations:
- darwin-arm64
- linux-x86_64 (x86_64 is same as amd64)

Take the page for [v2.3.1](https://github.com/starkware-libs/cairo/releases/tag/v2.3.1) for example. The Hardhat plugin for Starknet only supports these pre-built binaries out-of-the-box.

You'll probably need to clone the [starkware-libs/cairo](https://github.com/starkware-libs/cairo) repository, and follow the instructions on how to build the binaries for your combination of platform and architecture (probably just `cargo build` or `cargo build --release`). Then just follow the Hardhat plugin [documentation](https://0xspaceshard.github.io/starknet-hardhat-plugin/docs/intro/#starknet-compile) to see how to edit the  `cairo1BinDir` property of your `hardhat.config.ts` mentioned in the error output you provided.

I'll close this issue, but feel free to reopen.
